//Deku Sticks
export const ADD_DEKU_STICKS = "ADD_DEKU_STICKS";
export const REMOVE_DEKU_STICKS = "REMOVE_DEKU_STICKS";
export const ADD_FIRST_STICKS_UPGRADE = "ADD_FIRST_STICKS_UPGRADE";
export const REMOVE_FIRST_STICKS_UPGRADE = "REMOVE_FIRST_STICKS_UPGRADE";
export const ADD_SECOND_STICKS_UPGRADE = "ADD_SECOND_STICKS_UPGRADE";
export const REMOVE_SECOND_STICKS_UPGRADE = "REMOVE_SECOND_STICKS_UPGRADE";

//Skulltula Tokens

export const ADD_SKULLTULA = "ADD_SKULLTULA";
export const REMOVE_SKULLTULA = "REMOVE_SKULLTULA";