//First Row
//Deku Sticks
export const ADD_DEKU_STICKS = "ADD_DEKU_STICKS";
export const REMOVE_DEKU_STICKS = "REMOVE_DEKU_STICKS";

//Deku Nuts
export const ADD_DEKU_NUTS = "ADD_DEKU_NUTS";
export const REMOVE_DEKU_NUTS = "REMOVE_DEKU_NUTS";

//Bomb Bags
export const ADD_BOMBS = "ADD_BOMBS";
export const REMOVE_BOMBS = "REMOVE_BOMBS";

//Fairy Bow
export const ADD_FAIRY_BOW = "ADD_FAIRY_BOW";
export const REMOVE_FAIRY_BOW = "REMOVE_FAIRY_BOW";

//Fire Arrows
export const ADD_FIRE_ARROWS = "ADD_FIRE_ARROWS";
export const REMOVE_FIRE_ARROWS = "REMOVE_FIRE_ARROWS";

//Dins's Fire
export const ADD_DINS_FIRE = "ADD_DINS_FIRE";
export const REMOVE_DINS_FIRE = "REMOVE_DINS_FIRE";

//Kokiri Sword
export const ADD_KOKIRI_SWORD = "ADD_KOKIRI_SWORD";
export const REMOVE_KOKIRI_SWORD = "REMOVE_KOKIRI_SWORD";

//Second Row
//BiggoronSword
export const ADD_BIGGORON_SWORD = "ADD_BIGGORON_SWORD";
export const REMOVE_BIGGORON_SWORD = "REMOVE_BIGGORON_SWORD";

//Fairy Slingshot
export const ADD_FAIRY_SLINGSHOT = "ADD_FAIRY_SLINGSHOT";
export const REMOVE_FAIRY_SLINGSHOT = "REMOVE_FAIRY_SLINGSHOT";

//Ocarinas
export const ADD_FAIRY_OCARINA = "ADD_FAIRY_OCARINA";
export const REMOVE_FAIRY_OCARINA = "REMOVE_FAIRY_OCARINA";
export const ADD_OCARINA_OF_TIME = "ADD_OCARINA_OF_TIME";
export const REMOVE_OCARINA_OF_TIME = "REMOVE_OCARINA_OF_TIME";
 
//Bombchus
export const ADD_BOMBCHUS = "ADD_BOMBCHUS";
export const REMOVE_BOMBCHUS = "REMOVE_BOMBCHUS";

//Hookshot
export const ADD_HOOKSHOT = "ADD_HOOKSHOT";
export const REMOVE_HOOKSHOT = "REMOVE_HOOKSHOT";
export const ADD_LONGSHOT = "ADD_LONGSHOT";
export const REMOVE_LONGSHOT = "REMOVE_LONGSHOT";

//Ice Arrows
export const ADD_ICE_ARROWS = "ADD_ICE_ARROWS";
export const REMOVE_ICE_ARROWS = "REMOVE_ICE_ARROWS";

//Farore's Wind
export const ADD_FARORES_WIND = "ADD_FARORES_WIND";
export const REMOVE_FARORES_WIND = "REMOVE_FARORES_WIND";

//Deku Shield
export const ADD_DEKU_SHIELD = "ADD_DEKU_SHIELD";
export const REMOVE_DEKU_SHIELD = "REMOVE_DEKU_SHIELD";

//Third Row
//Hylian Shield
export const ADD_HYLIAN_SHIELD = "ADD_HYLIAN_SHIELD";
export const REMOVE_HYLIAN_SHIELD = "REMOVE_HYLIAN_SHIELD";

//Mirror Shield
export const ADD_MIRROR_SHIELD = "ADD_MIRROR_SHIELD";
export const REMOVE_MIRROR_SHIELD = "REMOVE_MIRROR_SHIELD";

//Boomerang
export const ADD_BOOMERANG = "ADD_BOOMERANG";
export const REMOVE_BOOMERANG = "REMOVE_BOOMERANG";

//Lens of Truth
export const ADD_LENS_OF_TRUTH = "ADD_LENS_OF_TRUTH";
export const REMOVE_LENS_OF_TRUTH = "REMOVE_LENS_OF_TRUTH";

//Magic Beans
export const ADD_MAGIC_BEANS = "ADD_MAGIC_BEANS";
export const REMOVE_MAGIC_BEANS = "REMOVE_MAGIC_BEANS";

//Megaton Hammer
export const ADD_MEGATON_HAMMER = "ADD_MEGATON_HAMMER";
export const REMOVE_MEGATON_HAMMER = "REMOVE_MEGATON_HAMMER";

//Light Arrows
export const ADD_LIGHT_ARROWS = "ADD_LIGHT_ARROWS";
export const REMOVE_LIGHT_ARROWS = "REMOVE_LIGHT_ARROWS";

//Nayru's Love
export const ADD_NAYRUS_LOVE = "ADD_NAYRUS_LOVE";
export const REMOVE_NAYRUS_LOVE = "REMOVE_NAYRUS_LOVE";

//Fourth Row
//Goron Tunic
export const ADD_GORON_TUNIC = "ADD_GORON_TUNIC";
export const REMOVE_GORON_TUNIC = "REMOVE_GORON_TUNIC";

//Zora Tunic
export const ADD_ZORA_TUNIC = "ADD_ZORA_TUNIC";
export const REMOVE_ZORA_TUNIC = "REMOVE_ZORA_TUNIC";

//Wallet
export const ADD_WALLET = "ADD_WALLET";
export const REMOVE_WALLET = "REMOVE_WALLET";

//Skulltula Tokens
export const ADD_SKULLTULA = "ADD_SKULLTULA";
export const REMOVE_SKULLTULA = "REMOVE_SKULLTULA";

//Empty Bottles
export const ADD_BOTTLE = "ADD_BOTTLE";
export const REMOVE_BOTTLE = "REMOVE_BOTTLE";

//Ruto's Letter
export const ADD_RUTOS_LETTER = "ADD_RUTOS_LETTER";
export const REMOVE_RUTOS_LETTER = "REMOVE_RUTOS_LETTER";

//Past Trading Sequence
export const ADD_WEIRD_EGG = "ADD_WEIRD_EGG";
export const REMOVE_WEIRD_EGG = "REMOVE_WEIRD_EGG";
export const ADD_CUCCO = "ADD_CUCCO";
export const REMOVE_CUCCO = "REMOVE_CUCCO";
export const ADD_ZELDAS_LETTER = "ADD_ZELDAS_LETTER";
export const REMOVE_ZELDAS_LETTER = "REMOVE_ZELDAS_LETTER";
export const ADD_KEATON_MASK = "ADD_KEATON_MASK";
export const REMOVE_KEATON_MASK = "REMOVE_KEATON_MASK";
export const ADD_SKULL_MASK = "ADD_SKULL_MASK";
export const REMOVE_SKULL_MASK = "REMOVE_SKULL_MASK";
export const ADD_SPOOKY_MASK = "ADD_SPOOKY_MASK";
export const REMOVE_SPOOKY_MASK = "REMOVE_SPOOKY_MASK";
export const ADD_BUNNY_HOOD = "ADD_BUNNY_HOOD";
export const REMOVE_BUNNY_HOOD = "REMOVE_BUNNY_HOOD";
export const ADD_MASK_OF_TRUTH = "ADD_MASK_OF_TRUTH";
export const REMOVE_MASK_OF_TRUTH = "REMOVE_MASK_OF_TRUTH";

//Fifth Row
//Future Trading Sequence
export const ADD_POCKET_EGG = "ADD_POCKET_EGG";
export const REMOVE_POCKET_EGG = "REMOVE_POCKET_EGG";
export const ADD_POCKET_CUCCO = "ADD_POCKET_CUCCO";
export const REMOVE_POCKET_CUCCO = "REMOVE_POCKET_CUCCO";
export const ADD_COJIRO = "ADD_COJIRO";
export const REMOVE_COJIRO = "REMOVE_COJIRO";
export const ADD_ODD_MUSHROOM = "ADD_ODD_MUSHROOM";
export const REMOVE_ODD_MUSHROOM = "REMOVE_ODD_MUSHROOM";
export const ADD_ODD_POTION = "ADD_ODD_POTION";
export const REMOVE_ODD_POTION = "REMOVE_ODD_POTION";
export const ADD_POACHERS_SAW = "ADD_POACHERS_SAW";
export const REMOVE_POACHERS_SAW = "REMOVE_POACHERS_SAW";
export const ADD_BROKEN_GORONS_SWORD = "ADD_BROKEN_GORONS_SWORD";
export const REMOVE_BROKEN_GORONS_SWORD = "REMOVE_BROKEN_GORONS_SWORD";
export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const REMOVE_PRESCRIPTION = "REMOVE_PRESCRIPTION";
export const ADD_EYEBALL_FROG = "ADD_EYEBALL_FROG";
export const REMOVE_EYEBALL_FROG = "REMOVE_EYEBALL_FROG";
export const ADD_EYE_DROPS = "ADD_EYE_DROPS";
export const REMOVE_EYE_DROPS = "REMOVE_EYE_DROPS";
export const ADD_CLAIM_CHECK = "ADD_CLAIM_CHECK";
export const REMOVE_CLAIM_CHECK = "REMOVE_CLAIM_CHECK";

//Iron Boots
export const ADD_IRON_BOOTS = "ADD_IRON_BOOTS";
export const REMOVE_IRON_BOOTS = "REMOVE_IRON_BOOTS";

//Hover Boots
export const ADD_HOVER_BOOTS = "ADD_HOVER_BOOTS";
export const REMOVE_HOVER_BOOTS = "REMOVE_HOVER_BOOTS";

//Zora Scales
export const ADD_SILVER_SCALE = "ADD_SILVER_SCALE";
export const REMOVE_SILVER_SCALE = "REMOVE_SILVER_SCALE";
export const ADD_GOLDEN_SCALE = "ADD_GOLDEN_SCALE";
export const REMOVE_GOLDEN_SCALE = "REMOVE_GOLDEN_SCALE";

//Magic Meter
export const ADD_MAGIC = "ADD_MAGIC";
export const REMOVE_MAGIC = "REMOVE_MAGIC";
export const ADD_DOUBLE_MAGIC = "ADD_DOUBLE_MAGIC";
export const REMOVE_DOUBLE_MAGIC = "REMOVE_DOUBLE_MAGIC";

//Strength Enhancers
export const ADD_GORONS_BRACELET = "ADD_GORONS_BRACELET";
export const REMOVE_GORONS_BRACELET = "REMOVE_GORONS_BRACELET";
export const ADD_SILVER_GAUNTLETS = "ADD_SILVER_GAUNTLETS";
export const REMOVE_SILVER_GAUNTLETS = "REMOVE_SILVER_GAUNTLETS";
export const ADD_GOLDEN_GAUNTLETS = "ADD_GOLDEN_GAUNTLETS";
export const REMOVE_GOLDEN_GAUNTLETS = "REMOVE_GOLDEN_GAUNTLETS";

//Gerudo Membership Card
export const ADD_GERUDO_CARD = "ADD_GERUDO_CARD";
export const REMOVE_GERUDO_CARD = "REMOVE_GERUDO_CARD";

//Sixth Row
//Stone/Shard of Agony
export const ADD_STONE_OF_AGONY = "ADD_STONE_OF_AGONY";
export const REMOVE_STONE_OF_AGONY = "REMOVE_STONE_OF_AGONY";

//Pieces of Heart
export const ADD_PIECE_OF_HEART = "ADD_PIECE_OF_HEART";
export const REMOVE_PIECE_OF_HEART = "REMOVE_PIECE_OF_HEART";

//Heart Containers
export const ADD_HEART_CONTAINER = "ADD_HEART_CONTAINER";
export const REMOVE_HEART_CONTAINER = "REMOVE_HEART_CONTAINER";

//Double Defense
export const ADD_DOUBLE_DEFENSE = "ADD_DOUBLE_DEFENSE";
export const REMOVE_DOUBLE_DEFENSE = "REMOVE_DOUBLE_DEFENSE";