//First Row
//Deku Sticks
export const ADD_DEKU_STICKS = "ADD_DEKU_STICKS";
export const REMOVE_DEKU_STICKS = "REMOVE_DEKU_STICKS";

//Deku Nuts
export const ADD_DEKU_NUTS = "ADD_DEKU_NUTS";
export const REMOVE_DEKU_NUTS = "REMOVE_DEKU_NUTS";

//Bomb Bags
export const ADD_BOMBS = "ADD_BOMBS";
export const REMOVE_BOMBS = "REMOVE_BOMBS";

//Fairy Bow
export const ADD_FAIRY_BOW = "ADD_FAIRY_BOW";
export const REMOVE_FAIRY_BOW = "REMOVE_FAIRY_BOW";

//Fire Arrows
export const ADD_FIRE_ARROWS = "ADD_FIRE_ARROWS";
export const REMOVE_FIRE_ARROWS = "REMOVE_FIRE_ARROWS";

//Dins's Fire
export const ADD_DINS_FIRE = "ADD_DINS_FIRE";
export const REMOVE_DINS_FIRE = "REMOVE_DINS_FIRE";

//Kokiri Sword
export const ADD_KOKIRI_SWORD = "ADD_KOKIRI_SWORD";
export const REMOVE_KOKIRI_SWORD = "REMOVE_KOKIRI_SWORD";

//Second Row
//BiggoronSword
export const ADD_BIGGORON_SWORD = "ADD_BIGGORON_SWORD";
export const REMOVE_BIGGORON_SWORD = "REMOVE_BIGGORON_SWORD";

//Fairy Slingshot
export const ADD_FAIRY_SLINGSHOT = "ADD_FAIRY_SLINGSHOT";
export const REMOVE_FAIRY_SLINGSHOT = "REMOVE_FAIRY_SLINGSHOT";

//Ocarinas
export const ADD_FAIRY_OCARINA = "ADD_FAIRY_OCARINA";
export const REMOVE_FAIRY_OCARINA = "REMOVE_FAIRY_OCARINA";
export const ADD_OCARINA_OF_TIME = "ADD_OCARINA_OF_TIME";
export const REMOVE_OCARINA_OF_TIME = "REMOVE_OCARINA_OF_TIME";
 
//Bombchus
export const ADD_BOMBCHUS = "ADD_BOMBCHUS";
export const REMOVE_BOMBCHUS = "REMOVE_BOMBCHUS";

//Hookshot
export const ADD_HOOKSHOT = "ADD_HOOKSHOT";
export const REMOVE_HOOKSHOT = "REMOVE_HOOKSHOT";
export const ADD_LONGSHOT = "ADD_LONGSHOT";
export const REMOVE_LONGSHOT = "REMOVE_LONGSHOT";

//Ice Arrows
export const ADD_ICE_ARROWS = "ADD_ICE_ARROWS";
export const REMOVE_ICE_ARROWS = "REMOVE_ICE_ARROWS";

//Farore's Wind
export const ADD_FARORES_WIND = "ADD_FARORES_WIND";
export const REMOVE_FARORES_WIND = "REMOVE_FARORES_WIND";

//Deku Shield
export const ADD_DEKU_SHIELD = "ADD_DEKU_SHIELD";
export const REMOVE_DEKU_SHIELD = "REMOVE_DEKU_SHIELD";

//Third Row
//Hylian Shield
export const ADD_HYLIAN_SHIELD = "ADD_HYLIAN_SHIELD";
export const REMOVE_HYLIAN_SHIELD = "REMOVE_HYLIAN_SHIELD";

//Mirror Shield
export const ADD_MIRROR_SHIELD = "ADD_MIRROR_SHIELD";
export const REMOVE_MIRROR_SHIELD = "REMOVE_MIRROR_SHIELD";

//Boomerang
export const ADD_BOOMERANG = "ADD_BOOMERANG";
export const REMOVE_BOOMERANG = "REMOVE_BOOMERANG";

//Lens of Truth
export const ADD_LENS_OF_TRUTH = "ADD_LENS_OF_TRUTH";
export const REMOVE_LENS_OF_TRUTH = "REMOVE_LENS_OF_TRUTH";

//Magic Beans
export const ADD_MAGIC_BEANS = "ADD_MAGIC_BEANS";
export const REMOVE_MAGIC_BEANS = "REMOVE_MAGIC_BEANS";

//Megaton Hammer
export const ADD_MEGATON_HAMMER = "ADD_MEGATON_HAMMER";
export const REMOVE_MEGATON_HAMMER = "REMOVE_MEGATON_HAMMER";

//Light Arrows
export const ADD_LIGHT_ARROWS = "ADD_LIGHT_ARROWS";
export const REMOVE_LIGHT_ARROWS = "REMOVE_LIGHT_ARROWS";

//Nayru's Love
export const ADD_NAYRUS_LOVE = "ADD_NAYRUS_LOVE";
export const REMOVE_NAYRUS_LOVE = "REMOVE_NAYRUS_LOVE";

//Fourth Row
//Goron Tunic
export const ADD_GORON_TUNIC = "ADD_GORON_TUNIC";
export const REMOVE_GORON_TUNIC = "REMOVE_GORON_TUNIC";

//Zora Tunic
export const ADD_ZORA_TUNIC = "ADD_ZORA_TUNIC";
export const REMOVE_ZORA_TUNIC = "REMOVE_ZORA_TUNIC";

//Wallet
export const ADD_WALLET = "ADD_WALLET";
export const REMOVE_WALLET = "REMOVE_WALLET";

//Skulltula Tokens
export const ADD_SKULLTULA = "ADD_SKULLTULA";
export const REMOVE_SKULLTULA = "REMOVE_SKULLTULA";

//Empty Bottles
export const ADD_BOTTLE = "ADD_BOTTLE";
export const REMOVE_BOTTLE = "REMOVE_BOTTLE";

//Ruto's Letter
export const ADD_RUTOS_LETTER = "ADD_RUTOS_LETTER";
export const REMOVE_RUTOS_LETTER = "REMOVE_RUTOS_LETTER";

//Past Trading Sequence
export const ADD_MALONS_EGG = "ADD_MALONS_EGG";
export const REMOVE_MALONS_EGG = "REMOVE_MALONS_EGG";
export const ADD_POCKET_CUCCO = "ADD_POCKET_CUCCO";
export const REMOVE_POCKET_CUCCO = "REMOVE_POCKET_CUCCO";
export const ADD_ZELDAS_LETTER = "ADD_ZELDAS_LETTER";
export const REMOVE_ZELDAS_LETTER = "REMOVE_ZELDAS_LETTER";
export const ADD_KEATON_MASK = "ADD_KEATON_MASK";
export const REMOVE_KEATON_MASK = "REMOVE_KEATON_MASK";
export const ADD_SKULL_MASK = "ADD_SKULL_MASK";
export const REMOVE_SKULL_MASK = "REMOVE_SKULL_MASK";
export const ADD_SPOOKY_MASK = "ADD_SPOOKY_MASK";
export const REMOVE_SPOOKY_MASK = "REMOVE_SPOOKY_MASK";
export const ADD_BUNNY_HOOD = "ADD_BUNNY_HOOD";
export const REMOVE_BUNNY_HOOD = "REMOVE_BUNNY_HOOD";
export const ADD_MASK_OF_TRUTH = "ADD_MASK_OF_TRUTH";
export const REMOVE_MASK_OF_TRUTH = "REMOVE_MASK_OF_TRUTH";