import {
    ADD_IRON_BOOTS, REMOVE_IRON_BOOTS,
    ADD_HOVER_BOOTS, REMOVE_HOVER_BOOTS,
    ADD_SILVER_SCALE, REMOVE_SILVER_SCALE,
    ADD_GOLDEN_SCALE, REMOVE_GOLDEN_SCALE,
    ADD_MAGIC, REMOVE_MAGIC,
    ADD_DOUBLE_MAGIC, REMOVE_DOUBLE_MAGIC,
    ADD_GORONS_BRACELET, REMOVE_GORONS_BRACELET,
    ADD_SILVER_GAUNTLETS, REMOVE_SILVER_GAUNTLETS,
    ADD_GOLDEN_GAUNTLETS, REMOVE_GOLDEN_GAUNTLETS,
    ADD_GERUDO_CARD, REMOVE_GERUDO_CARD,
    ADD_POCKET_EGG, REMOVE_POCKET_EGG,
    ADD_POCKET_CUCCO, REMOVE_POCKET_CUCCO,
    ADD_COJIRO, REMOVE_COJIRO,
    ADD_ODD_MUSHROOM, REMOVE_ODD_MUSHROOM,
    ADD_ODD_POTION, REMOVE_ODD_POTION,
    ADD_POACHERS_SAW, REMOVE_POACHERS_SAW,
    ADD_BROKEN_GORONS_SWORD, REMOVE_BROKEN_GORONS_SWORD,
    ADD_PRESCRIPTION, REMOVE_PRESCRIPTION,
    ADD_EYEBALL_FROG, REMOVE_EYEBALL_FROG,
    ADD_EYE_DROPS, REMOVE_EYE_DROPS,
    ADD_CLAIM_CHECK, REMOVE_CLAIM_CHECK
} from "../actions/types";

let INITIAL_STATE = {
    ironBoots: null,
    hoverBoots: null,
    silverScale: null,
    goldenSCale: null,
    magic: null,
    doubleMagic: null,
    goronsBracelet: null,
    silverGauntlets: null,
    goldenGauntlets: null,
    gerudoCard: null,
    pocketEgg: null, 
    pocketCucco: null,
    cojiro: null,
    oddMushroom: null,
    oddPotion: null,
    poachersSaw: null,
    brokenGoronsSword: null,
    prescription: null,
    eyeballFrog: null,
    eyeDrops: null,
    claimCheck: null
};